"""
Seed volunteer events for major US cities
Static events with nonprofit contact information
"""

from datetime import datetime, timedelta, timezone


# Generate upcoming dates
def get_upcoming_dates(count=10):
    """Generate upcoming dates for events"""
    today = datetime.now(timezone.utc)
    return [(today + timedelta(days=i * 3)).isoformat() for i in range(count)]


dates = get_upcoming_dates()

SEED_EVENTS = [
    # NEW YORK, NY
    {
        "title": "Community Food Bank - Meal Preparation",
        "organization": "City Harvest",
        "description": "Help prepare and pack meals for families in need. No experience necessary - training provided on-site.",
        "date_start": dates[0],
        "location_address": "150 52nd Street",
        "city": "New York",
        "state": "NY",
        "zip": "10019",
        "latitude": 40.7614,
        "longitude": -73.9776,
        "category": "Hunger Relief",
        "url": "https://www.cityharvest.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@cityharvest.org",
        "contact_phone": "(646) 412-0600",
    },
    {
        "title": "Animal Shelter Volunteer",
        "organization": "ASPCA",
        "description": "Spend time with shelter animals, help with feeding, walking, and socialization. Make a difference in an animal's life!",
        "date_start": dates[1],
        "location_address": "424 E 92nd St",
        "city": "New York",
        "state": "NY",
        "zip": "10128",
        "latitude": 40.7812,
        "longitude": -73.9467,
        "category": "Animal Welfare",
        "url": "https://www.aspca.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@aspca.org",
        "contact_phone": "(212) 876-7700",
    },
    {
        "title": "Park Cleanup & Tree Planting",
        "organization": "Central Park Conservancy",
        "description": "Join us for a morning of beautifying Central Park. Help with cleanup, planting, and trail maintenance.",
        "date_start": dates[2],
        "location_address": "14 E 60th St",
        "city": "New York",
        "state": "NY",
        "zip": "10022",
        "latitude": 40.7676,
        "longitude": -73.9728,
        "category": "Environment",
        "url": "https://www.centralparknyc.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@centralparknyc.org",
        "contact_phone": "(212) 310-6600",
    },
    # LOS ANGELES, CA
    {
        "title": "Beach Cleanup Volunteer Day",
        "organization": "Heal the Bay",
        "description": "Help keep our beaches clean! Remove trash and debris from Santa Monica Beach. All supplies provided.",
        "date_start": dates[0],
        "location_address": "1600 Ocean Front Walk",
        "city": "Santa Monica",
        "state": "CA",
        "zip": "90401",
        "latitude": 34.0097,
        "longitude": -118.4966,
        "category": "Environment",
        "url": "https://healthebay.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@healthebay.org",
        "contact_phone": "(310) 451-1500",
    },
    {
        "title": "Homeless Shelter Meal Service",
        "organization": "LA Mission",
        "description": "Serve meals to homeless individuals and families. Help with food preparation, serving, and cleanup.",
        "date_start": dates[1],
        "location_address": "303 E 5th St",
        "city": "Los Angeles",
        "state": "CA",
        "zip": "90013",
        "latitude": 34.0447,
        "longitude": -118.2446,
        "category": "Hunger Relief",
        "url": "https://www.lamission.net/volunteer",
        "source": "Static",
        "contact_email": "volunteer@lamission.net",
        "contact_phone": "(213) 629-1227",
    },
    {
        "title": "Youth Tutoring & Mentoring",
        "organization": "Boys & Girls Clubs of LA",
        "description": "Mentor and tutor youth after school. Help with homework, reading, and educational activities.",
        "date_start": dates[2],
        "location_address": "350 S Figueroa St",
        "city": "Los Angeles",
        "state": "CA",
        "zip": "90071",
        "latitude": 34.0522,
        "longitude": -118.2521,
        "category": "Education",
        "url": "https://www.bgcla.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@bgcla.org",
        "contact_phone": "(213) 235-6010",
    },
    # CHICAGO, IL
    {
        "title": "Food Pantry Volunteer",
        "organization": "Greater Chicago Food Depository",
        "description": "Sort and pack food donations for distribution to families in need. Perfect for groups or individuals.",
        "date_start": dates[0],
        "location_address": "4100 W Ann Lurie Pl",
        "city": "Chicago",
        "state": "IL",
        "zip": "60632",
        "latitude": 41.8207,
        "longitude": -87.7282,
        "category": "Hunger Relief",
        "url": "https://www.chicagosfoodbank.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@gcfd.org",
        "contact_phone": "(773) 247-3663",
    },
    {
        "title": "Senior Center Activities Assistant",
        "organization": "Chicago Senior Centers",
        "description": "Assist seniors with activities, games, and social programs. Bring joy to older adults in our community.",
        "date_start": dates[1],
        "location_address": "618 S Michigan Ave",
        "city": "Chicago",
        "state": "IL",
        "zip": "60605",
        "latitude": 41.8758,
        "longitude": -87.6246,
        "category": "Seniors",
        "url": "https://www.chicagoseniorcenter.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@chicagoseniorcenter.org",
        "contact_phone": "(312) 745-4420",
    },
    # HOUSTON, TX
    {
        "title": "Habitat for Humanity Build Day",
        "organization": "Habitat for Humanity Houston",
        "description": "Help build homes for families in need. No construction experience required - we'll teach you!",
        "date_start": dates[0],
        "location_address": "2500 Tanglewilde St",
        "city": "Houston",
        "state": "TX",
        "zip": "77063",
        "latitude": 29.7416,
        "longitude": -95.5001,
        "category": "Community",
        "url": "https://www.habitathouston.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@habitathouston.org",
        "contact_phone": "(713) 766-4663",
    },
    {
        "title": "Animal Rescue & Adoption Event",
        "organization": "Houston Pets Alive",
        "description": "Help with adoption events, animal care, and community outreach. Make a difference for homeless pets!",
        "date_start": dates[1],
        "location_address": "8620 Stella Link Rd",
        "city": "Houston",
        "state": "TX",
        "zip": "77025",
        "latitude": 29.6919,
        "longitude": -95.4368,
        "category": "Animal Welfare",
        "url": "https://www.houstonpetsalive.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@houstonpetsalive.org",
        "contact_phone": "(713) 880-8040",
    },
    # DALLAS, TX
    {
        "title": "North Texas Food Bank Distribution",
        "organization": "North Texas Food Bank",
        "description": "Pack and distribute food boxes for families facing hunger. Every hour makes a huge impact!",
        "date_start": dates[0],
        "location_address": "3677 Mapleshade Ln",
        "city": "Dallas",
        "state": "TX",
        "zip": "75212",
        "latitude": 32.8320,
        "longitude": -96.8806,
        "category": "Hunger Relief",
        "url": "https://www.ntfb.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@ntfb.org",
        "contact_phone": "(214) 330-1396",
    },
    {
        "title": "Youth Soccer Coaching & Mentoring",
        "organization": "Dallas Youth Sports",
        "description": "Coach youth soccer and provide mentorship to kids in underserved communities. Sports equipment provided.",
        "date_start": dates[1],
        "location_address": "1500 Marilla St",
        "city": "Dallas",
        "state": "TX",
        "zip": "75201",
        "latitude": 32.7767,
        "longitude": -96.7970,
        "category": "Education",
        "url": "https://www.dallasyouthsports.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@dallasyouthsports.org",
        "contact_phone": "(214) 670-8418",
    },
    {
        "title": "Community Garden Project",
        "organization": "Dallas Community Gardens",
        "description": "Help maintain community gardens, teach sustainable farming, and distribute fresh produce to neighbors.",
        "date_start": dates[2],
        "location_address": "3809 Grand Ave",
        "city": "Dallas",
        "state": "TX",
        "zip": "75210",
        "latitude": 32.7545,
        "longitude": -96.7677,
        "category": "Environment",
        "url": "https://www.dallasgardens.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@dallasgardens.org",
        "contact_phone": "(214) 555-0100",
    },
    # PHOENIX, AZ
    {
        "title": "Desert Wildlife Rescue",
        "organization": "Arizona Wildlife Rescue",
        "description": "Assist with wildlife rehabilitation, feeding, and release preparation. Learn about desert ecology!",
        "date_start": dates[0],
        "location_address": "2710 N 20th St",
        "city": "Phoenix",
        "state": "AZ",
        "zip": "85006",
        "latitude": 33.4740,
        "longitude": -112.0429,
        "category": "Animal Welfare",
        "url": "https://www.azwildliferescue.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@azwildliferescue.org",
        "contact_phone": "(602) 273-3929",
    },
    {
        "title": "Homeless Outreach Team",
        "organization": "Phoenix Rescue Mission",
        "description": "Distribute meals, water, and supplies to homeless individuals. Make a direct impact on lives.",
        "date_start": dates[1],
        "location_address": "1801 S 35th Ave",
        "city": "Phoenix",
        "state": "AZ",
        "zip": "85009",
        "latitude": 33.4354,
        "longitude": -112.1286,
        "category": "Hunger Relief",
        "url": "https://www.phoenixrescuemission.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@prm.org",
        "contact_phone": "(602) 233-3000",
    },
    # AUSTIN, TX
    {
        "title": "Keep Austin Beautiful Cleanup",
        "organization": "Keep Austin Beautiful",
        "description": "Join citywide cleanup efforts. Remove litter, plant trees, and beautify public spaces.",
        "date_start": dates[0],
        "location_address": "505 Barton Springs Rd",
        "city": "Austin",
        "state": "TX",
        "zip": "78704",
        "latitude": 30.2640,
        "longitude": -97.7699,
        "category": "Environment",
        "url": "https://www.keepaustinbeautiful.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@keepaustinbeautiful.org",
        "contact_phone": "(512) 391-0617",
    },
    {
        "title": "Tech Literacy for Seniors",
        "organization": "Austin Tech Tutors",
        "description": "Teach seniors how to use smartphones, computers, and the internet. Help bridge the digital divide.",
        "date_start": dates[1],
        "location_address": "700 Lavaca St",
        "city": "Austin",
        "state": "TX",
        "zip": "78701",
        "latitude": 30.2711,
        "longitude": -97.7437,
        "category": "Seniors",
        "url": "https://www.austintechtutors.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@austintechtutors.org",
        "contact_phone": "(512) 555-0200",
    },
    # SAN FRANCISCO, CA
    {
        "title": "Food Recovery & Distribution",
        "organization": "SF-Marin Food Bank",
        "description": "Rescue surplus food from businesses and deliver to families in need. Help reduce food waste!",
        "date_start": dates[0],
        "location_address": "900 Pennsylvania Ave",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94107",
        "latitude": 37.7583,
        "longitude": -122.3972,
        "category": "Hunger Relief",
        "url": "https://www.sfmfoodbank.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@sfmfoodbank.org",
        "contact_phone": "(415) 282-1900",
    },
    {
        "title": "Bay Area Trail Maintenance",
        "organization": "Golden Gate National Parks Conservancy",
        "description": "Maintain hiking trails, restore native plants, and preserve natural habitats in the Bay Area.",
        "date_start": dates[1],
        "location_address": "Building 201 Fort Mason",
        "city": "San Francisco",
        "state": "CA",
        "zip": "94123",
        "latitude": 37.8057,
        "longitude": -122.4314,
        "category": "Environment",
        "url": "https://www.parksconservancy.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@parksconservancy.org",
        "contact_phone": "(415) 561-3000",
    },
    # SEATTLE, WA
    {
        "title": "Food Bank Sorting & Packing",
        "organization": "Northwest Harvest",
        "description": "Sort and pack food donations for distribution across Washington. Family-friendly volunteer opportunity.",
        "date_start": dates[0],
        "location_address": "7700 W Marginal Way S",
        "city": "Seattle",
        "state": "WA",
        "zip": "98108",
        "latitude": 47.5341,
        "longitude": -122.3409,
        "category": "Hunger Relief",
        "url": "https://www.northwestharvest.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@northwestharvest.org",
        "contact_phone": "(206) 625-0755",
    },
    {
        "title": "Puget Sound Beach Cleanup",
        "organization": "Seattle Aquarium",
        "description": "Help protect marine life by cleaning up beaches and documenting debris. Learn about ocean conservation.",
        "date_start": dates[1],
        "location_address": "1483 Alaskan Way",
        "city": "Seattle",
        "state": "WA",
        "zip": "98101",
        "latitude": 47.6074,
        "longitude": -122.3429,
        "category": "Environment",
        "url": "https://www.seattleaquarium.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@seattleaquarium.org",
        "contact_phone": "(206) 386-4300",
    },
    # BOSTON, MA
    {
        "title": "Greater Boston Food Bank",
        "organization": "The Greater Boston Food Bank",
        "description": "Sort and repack food for distribution to local pantries. Help fight hunger in Massachusetts.",
        "date_start": dates[0],
        "location_address": "70 South Bay Ave",
        "city": "Boston",
        "state": "MA",
        "zip": "02118",
        "latitude": 42.3351,
        "longitude": -71.0653,
        "category": "Hunger Relief",
        "url": "https://www.gbfb.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@gbfb.org",
        "contact_phone": "(617) 427-5200",
    },
    {
        "title": "Youth Literacy Program",
        "organization": "Boston Public Library",
        "description": "Tutor children in reading and literacy skills. Help build a foundation for lifelong learning.",
        "date_start": dates[1],
        "location_address": "700 Boylston St",
        "city": "Boston",
        "state": "MA",
        "zip": "02116",
        "latitude": 42.3493,
        "longitude": -71.0783,
        "category": "Education",
        "url": "https://www.bpl.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@bpl.org",
        "contact_phone": "(617) 536-5400",
    },
    # MIAMI, FL
    {
        "title": "Coastal Cleanup & Marine Conservation",
        "organization": "Miami Waterkeeper",
        "description": "Clean up beaches and waterways, protect marine ecosystems, and raise awareness about water quality.",
        "date_start": dates[0],
        "location_address": "3000 Biscayne Blvd",
        "city": "Miami",
        "state": "FL",
        "zip": "33137",
        "latitude": 25.8064,
        "longitude": -80.1867,
        "category": "Environment",
        "url": "https://www.miamiwaterkeeper.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@miamiwaterkeeper.org",
        "contact_phone": "(305) 905-0856",
    },
    {
        "title": "Feeding South Florida Volunteer",
        "organization": "Feeding South Florida",
        "description": "Pack and distribute food to families in need. Help address food insecurity in our community.",
        "date_start": dates[1],
        "location_address": "2501 SW 32nd Terrace",
        "city": "Pembroke Park",
        "state": "FL",
        "zip": "33023",
        "latitude": 25.9863,
        "longitude": -80.1724,
        "category": "Hunger Relief",
        "url": "https://www.feedingsouthflorida.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@feedingsouthflorida.org",
        "contact_phone": "(954) 518-1818",
    },
    # DENVER, CO
    {
        "title": "Mountain Park Trail Maintenance",
        "organization": "Rocky Mountain Conservancy",
        "description": "Maintain trails, restore habitats, and preserve Colorado's natural beauty. Outdoor adventure meets community service!",
        "date_start": dates[0],
        "location_address": "1895 Fall River Rd",
        "city": "Estes Park",
        "state": "CO",
        "zip": "80517",
        "latitude": 40.3833,
        "longitude": -105.5728,
        "category": "Environment",
        "url": "https://www.rmconservancy.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@rmconservancy.org",
        "contact_phone": "(970) 586-3262",
    },
    {
        "title": "Urban Farming & Food Justice",
        "organization": "Denver Urban Gardens",
        "description": "Work in community gardens, teach sustainable farming, and distribute fresh produce to food deserts.",
        "date_start": dates[1],
        "location_address": "1031 33rd St",
        "city": "Denver",
        "state": "CO",
        "zip": "80205",
        "latitude": 39.7643,
        "longitude": -105.0068,
        "category": "Environment",
        "url": "https://www.dug.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@dug.org",
        "contact_phone": "(303) 292-9900",
    },
    # ATLANTA, GA
    {
        "title": "Atlanta Community Food Bank",
        "organization": "Atlanta Community Food Bank",
        "description": "Sort food, pack boxes, and help distribute meals to families facing hunger across Metro Atlanta.",
        "date_start": dates[0],
        "location_address": "732 Joseph E Lowery Blvd NW",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "latitude": 33.7710,
        "longitude": -84.4230,
        "category": "Hunger Relief",
        "url": "https://www.acfb.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@acfb.org",
        "contact_phone": "(404) 892-9822",
    },
    {
        "title": "Habitat Restoration at Chattahoochee River",
        "organization": "Chattahoochee Riverkeeper",
        "description": "Remove invasive species, plant native vegetation, and restore river habitats. Protect Atlanta's water source!",
        "date_start": dates[1],
        "location_address": "3 Puritan Mill",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "latitude": 33.8065,
        "longitude": -84.4101,
        "category": "Environment",
        "url": "https://www.chattahoochee.org/volunteer",
        "source": "Static",
        "contact_email": "volunteer@chattahoochee.org",
        "contact_phone": "(404) 352-9828",
    },
]
