export const CATEGORIES = [
  "All",
  "Animal Welfare",
  "Arts & Culture",
  "Children & Youth",
  "Community Development",
  "Disaster Relief",
  "Education & Literacy",
  "Environment",
  "Health & Medicine",
  "Human Rights",
  "Seniors",
  "Social Services",
  "Sports & Recreation",
  "Technology",
  "Women's Issues",
];
